// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroTrack.Context;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NeuroTrack.Migrations
{
    [DbContext(typeof(NeuroTrackContext))]
    [Migration("20251123003257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeuroTrack.Models.GsDailyLogs", b =>
                {
                    b.Property<decimal>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdLog"));

                    b.Property<decimal>("IdUser")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_USER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("DATE")
                        .HasColumnName("LOG_DATE");

                    b.Property<byte>("Meetings")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("MEETINGS");

                    b.Property<byte>("WorkHours")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("WORK_HOURS");

                    b.HasKey("IdLog")
                        .HasName("PK_GS_DAILY_LOGS");

                    b.HasIndex("IdUser");

                    b.ToTable("GS_DAILY_LOGS", (string)null);
                });

            modelBuilder.Entity("NeuroTrack.Models.GsLimits", b =>
                {
                    b.Property<decimal>("IdLimits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_LIMITS");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdLimits"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_AT");

                    b.Property<byte>("LimitHours")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("LIMIT_HOURS");

                    b.Property<byte>("LimitMeetings")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("LIMIT_MEETINGS");

                    b.HasKey("IdLimits")
                        .HasName("PK_GS_LIMITS");

                    b.ToTable("GS_LIMITS", (string)null);
                });

            modelBuilder.Entity("NeuroTrack.Models.GsPredictions", b =>
                {
                    b.Property<decimal>("IdPrediction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_PREDICTION");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdPrediction"));

                    b.Property<DateTime>("DatePredicted")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_PREDICTED");

                    b.Property<decimal>("IdScores")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_SCORES");

                    b.Property<decimal>("IdStatusRisk")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_STATUS_RISK");

                    b.Property<decimal>("IdUser")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_USER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("MESSAGE");

                    b.Property<float>("StressPredicted")
                        .HasColumnType("FLOAT(2)")
                        .HasColumnName("STRESS_PREDICTED");

                    b.HasKey("IdPrediction")
                        .HasName("PK_GS_PREDICTIONS");

                    b.HasIndex("IdScores");

                    b.HasIndex("IdStatusRisk");

                    b.HasIndex("IdUser");

                    b.ToTable("GS_PREDICTIONS", (string)null);
                });

            modelBuilder.Entity("NeuroTrack.Models.GsRole", b =>
                {
                    b.Property<decimal>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_ROLE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdRole"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("IdRole")
                        .HasName("PK_GS_ROLE");

                    b.ToTable("GS_ROLE", (string)null);
                });

            modelBuilder.Entity("NeuroTrack.Models.GsScores", b =>
                {
                    b.Property<decimal>("IdScores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_SCORES");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdScores"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DateScore")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_SCORE");

                    b.Property<decimal>("IdLog")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_LOG");

                    b.Property<decimal>("IdStatusRisk")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_STATUS_RISK");

                    b.Property<decimal>("IdUser")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_USER");

                    b.Property<float>("ScoreValue")
                        .HasColumnType("FLOAT(4)")
                        .HasColumnName("SCORE_VALUE");

                    b.Property<byte>("TimeRecommendation")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("TIME_RECOMMENDATION");

                    b.HasKey("IdScores")
                        .HasName("PK_GS_SCORES");

                    b.HasIndex("IdLog")
                        .IsUnique();

                    b.HasIndex("IdStatusRisk");

                    b.HasIndex("IdUser");

                    b.ToTable("GS_SCORES", (string)null);
                });

            modelBuilder.Entity("NeuroTrack.Models.GsStatusRisk", b =>
                {
                    b.Property<decimal>("IdStatusRisk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_STATUS_RISK");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdStatusRisk"));

                    b.Property<string>("StatusNameRisk")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("STATUS_NAME_RISK");

                    b.HasKey("IdStatusRisk")
                        .HasName("PK_GS_STATUS_RISK");

                    b.ToTable("GS_STATUS_RISK", (string)null);
                });

            modelBuilder.Entity("NeuroTrack.Models.GsUsers", b =>
                {
                    b.Property<decimal>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_USER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdUser"));

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("EMAIL_USER");

                    b.Property<decimal>("IdLimits")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_LIMITS");

                    b.Property<decimal>("IdRole")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_ROLE");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME_USER");

                    b.Property<string>("PasswordUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_USER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdUser")
                        .HasName("PK_GS_USERS");

                    b.HasIndex("EmailUser")
                        .IsUnique()
                        .HasDatabaseName("UK_GS_USERS_EMAIL_USER");

                    b.HasIndex("IdLimits")
                        .IsUnique();

                    b.HasIndex("IdRole");

                    b.ToTable("GS_USERS", (string)null);
                });

            modelBuilder.Entity("NeuroTrack.Models.GsDailyLogs", b =>
                {
                    b.HasOne("NeuroTrack.Models.GsUsers", "GsUsers")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_USER_GS_DAILY_LOGS");

                    b.Navigation("GsUsers");
                });

            modelBuilder.Entity("NeuroTrack.Models.GsPredictions", b =>
                {
                    b.HasOne("NeuroTrack.Models.GsScores", "GsScores")
                        .WithMany()
                        .HasForeignKey("IdScores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_SCORES_GS_PREDICTIONS");

                    b.HasOne("NeuroTrack.Models.GsStatusRisk", "GsStatusRisk")
                        .WithMany()
                        .HasForeignKey("IdStatusRisk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_STATUS_RISK_GS_PREDICTIONS");

                    b.HasOne("NeuroTrack.Models.GsUsers", "GsUsers")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_USER_GS_PREDICTIONS");

                    b.Navigation("GsScores");

                    b.Navigation("GsStatusRisk");

                    b.Navigation("GsUsers");
                });

            modelBuilder.Entity("NeuroTrack.Models.GsScores", b =>
                {
                    b.HasOne("NeuroTrack.Models.GsDailyLogs", "GsDailyLogs")
                        .WithOne()
                        .HasForeignKey("NeuroTrack.Models.GsScores", "IdLog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_DAILY_LOGS_GS_SCORES");

                    b.HasOne("NeuroTrack.Models.GsStatusRisk", "GsStatusRisk")
                        .WithMany()
                        .HasForeignKey("IdStatusRisk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_STATUS_RISK_GS_SCORES");

                    b.HasOne("NeuroTrack.Models.GsUsers", "GsUsers")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_USER_GS_SCORES");

                    b.Navigation("GsDailyLogs");

                    b.Navigation("GsStatusRisk");

                    b.Navigation("GsUsers");
                });

            modelBuilder.Entity("NeuroTrack.Models.GsUsers", b =>
                {
                    b.HasOne("NeuroTrack.Models.GsLimits", "GsLimits")
                        .WithOne()
                        .HasForeignKey("NeuroTrack.Models.GsUsers", "IdLimits")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_LIMITS_GS_USERS");

                    b.HasOne("NeuroTrack.Models.GsRole", "GsRole")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_ROLE_GS_USERS");

                    b.Navigation("GsLimits");

                    b.Navigation("GsRole");
                });
#pragma warning restore 612, 618
        }
    }
}
